name: Build & Deploy Spring app

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Debug - Check folder structure
        run: ls -R

      - name: Unit Tests
        working-directory: jpa
        run: mvn -B test

      - name: Build the application
        working-directory: jpa
        run: |
          mvn clean
          mvn -B package
