spring :
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database : postgresql
    show-sql: true

