name: Build & Deploy Spring app

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Debug - List files
        run: ls -R

      - name: Unit Tests
        run: mvn -B test -f jpa/pom.xml

      - name: Build the application
        run: mvn -B package -f jpa/pom.xml
